[package]
name = "finance-together"
version = "0.1.0"
edition = "2024"

[dependencies]
libloading = "0.8.8"
tokio = "1.47.1"
lazy_thread_local = "0.1.2"
uuid = { version = "1.18.1", features = ["v4"] }
anyhow = "1.0.100"
thiserror = "2.0.16"
derive_more = { version = "2.0.1", features = ["display"] }
jsonschema = "0.33.0"
serde_json = "1.0.145"
serde = {version = "1.0.226", features = ["derive"] }
topo_sort = "0.4.0"
threadpool = "1.8.1"
parking_lot = "0.12.5"
ctrlc = "3.5.0"

finance-together-api = { path = "../api" }
