[package]
name = "finance-together-api"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = "2.0.16"
derive_more = { version = "2.0.1", features = ["display"] }
derive-enum-from-into = "0.2.0"
uuid = { version = "1", optional = true }
concat-idents = { version = "1.1.5", optional = true }
trait_fn = { path = "../trait_fn", optional = true }

[build-dependencies]
bindgen_helpers = "0.5.0"
cbindgen = "0.29.2"
cc = "1.2.44"

#const-assert = "1.0.1"

[lib]
crate-type = ["staticlib", "lib"]

[features]
default = ["safe"]
safe = ["dep:uuid", "dep:concat-idents", "dep:trait_fn"]
