[package]
name = "finance-together-api"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
thiserror = "2.0.16"
derive_more = {version = "2.0.1", features = ["display"]}

[build-dependencies]
bindgen = "0.72.1"
cbindgen = "0.29.0"
cc = "1.2.38"

[lib]
crate-type = ["staticlib", "lib"]